### ISSUE TITLE
Toggle element is always on

### ISSUE THREAD

**Issue by sebabal** [laraform/laraform#14] opened 2019-10-03 22:25 UTC
Hi, it seems the toggle element is always rendered as "ON". The data is saved correctly at the database but it seems the switch is set "OFF" if the value is "null".

I tried different "falseValue" such as 0, false, off, etc but they all have the same behaviour.

Any ideas?

**Comment by laraform** [comment] 2019-10-04 05:49
Looks like having set to `OFF` on `null` is the expected behavior but I'm not sure if I get the use case right. Can you provide an example code?

**Comment by gmartinez** [comment] 2019-10-04 13:24
Our understanding of the toggle control is that it should allow to toggle between two values specified by the "trueValue" and "falseValue", when the falseValue is set to other than null then even though the submit correctly saves the changes, then when loading again the record/form the toggle looks on (even though the value assigned to it is that specified in falseValue).

**Comment by sebabal** [comment] 2019-10-04 14:16
@laraform here is my schema it is a simple form that uses a toggle. It is kind of weird that it is the expected behaviour and also have the ability to set a falseValue if the only viable value is 'null'

```
return [
       ....fieds...
            'status' => [
                'type' => 'toggle',
                'falseValue' => 'unpublished',
		'trueValue' => 'published',
                'text' => 'Published?'
            ]
        ];
    }`
```

**Comment by laraform** [comment] 2019-10-06 21:52
Indeed loading the `falseValue`'s value did set the toggle to `on` instead of `off`. Patch will come this week.

**Closed as completed** 2019-11-29 10:33 UTC
